version: '3.8'

services:
  app:
    image: golang:latest
    container_name: go-app
    working_dir: /go/src/app
    volumes:
      - .:/go/src/app
    ports:
      - '8080:8080'
    networks:
      - go-microservice-network

  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    networks:
      - go-microservice-network

networks:
  go-microservice-network:
    driver: bridge
